Fix compile-time error due to Thread.Builder API
Thread.Builder API is being added as the API, and caused the following
error:

AggregationSuggestionEngine.java:221: error: incompatible types:
android.provider.ContactsContract.Contacts.AggregationSuggestions.Builder
cannot be converted to java.lang.Thread.Builder

Flag: EXEMPT refactor
Bug: 346542404
Test: m Contacts
Change-Id: I79d1d41349adbbe9d316d851bf7c581b2f64dc0e